name: Test GHCR Backend Push

on:
  workflow_dispatch:   # Se ejecuta a mano desde Actions

env:
  REGISTRY: ghcr.io
  IMAGE_BACK: ghcr.io/vicent301/ing-sw3-backend

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend            # << TU backend está en esta carpeta
          file: ./docker/api/Dockerfile # << TU Dockerfile está acá
          push: true
          tags: |
            ${{ env.IMAGE_BACK }}:qa
            ${{ env.IMAGE_BACK }}:latest
